a.out : LinkList.o main.o LinkList.h
	gcc -Wall -o a.out main.o LinkList.o

main.o : 11121281_4.c LinkList.h
	gcc -Wall -c -o main.o 11121281_4.c 

LinkList.o : LinkList.c LinkList.h
	gcc -Wall -c -o LinkList.o LinkList.c -lm

